/**
 * Pure input/output types for the FR-01 six-dimension readiness score.
 *
 * These shapes describe the *calculation layer* only. Nothing here talks to
 * Prisma — a later task (the Server Action in `actions/assessment.ts`) is
 * responsible for reading `Brand` and `Retailer.requirements` (JSON) and
 * mapping them onto these types before calling into `dimensions.ts`.
 *
 * Weights are the PRD's corrected set (§6.1 FR-01): the original table
 * summed to 110% because Fulfillment was added as a net-new dimension
 * without rebalancing the rest. Corrected weights sum to exactly 100%.
 */

// ---------------------------------------------------------------------------
// Shared result shape
// ---------------------------------------------------------------------------

/**
 * The result of scoring a single dimension.
 *
 * `reason` is a short, factual sentence describing *why* the score landed
 * where it did (numbers, thresholds, booleans) — not founder-facing prose.
 * The polished narrative for the surfaced blocker is generated by Claude in
 * a later task (FR-03's generation+verification pass); this layer only
 * needs to hand that later step true facts to work from, via `facts`.
 */
export interface DimensionScore<TFacts> {
  /** 0-100, always an integer (the Assessment columns this feeds are `Int`). */
  score: number;
  /** Short factual explanation of the score — not the founder-facing narrative. */
  reason: string;
  /** Structured facts backing `reason`, for a later task to narrate from. */
  facts: TFacts;
}

// ---------------------------------------------------------------------------
// Margin Readiness — 27%
// ---------------------------------------------------------------------------

/** Does wholesale pricing leave the retailer at their minimum gross margin? */
export interface MarginReadinessInput {
  /** Wholesale (brand-to-retailer/distributor) unit price, in USD. */
  wholesalePrice: number;
  /** Expected/suggested retail shelf price, in USD. */
  retailPrice: number;
  /** Retailer's minimum required gross margin, as a percentage (e.g. 40 for 40%). */
  retailerMinGrossMarginPct: number;
}

export interface MarginFacts {
  wholesalePrice: number;
  retailPrice: number;
  /** (retailPrice - wholesalePrice) / retailPrice * 100 */
  actualMarginPct: number;
  requiredMarginPct: number;
  /** actualMarginPct - requiredMarginPct. Negative means below the minimum. */
  marginSurplusPct: number;
}

// ---------------------------------------------------------------------------
// Distributor Readiness — 23%
// ---------------------------------------------------------------------------

/** Is a KeHE or UNFI relationship in place? Are EDI and EFT capability established? */
export interface DistributorReadinessInput {
  hasKeheRelationship: boolean;
  hasUnfiRelationship: boolean;
  /** Electronic Data Interchange — required to receive/process retailer POs. */
  ediCapable: boolean;
  /** Electronic Funds Transfer — required for distributor/retailer payment terms. */
  eftCapable: boolean;
}

export interface DistributorFacts extends DistributorReadinessInput {
  hasDistributorRelationship: boolean;
}

// ---------------------------------------------------------------------------
// Certification Readiness — 18%
// ---------------------------------------------------------------------------

export type CertificationType =
  | "usda_organic"
  | "non_gmo"
  | "gluten_free"
  | "sqf"
  | "brc";

/** USDA Organic, Non-GMO, Gluten-Free, and food safety certs (SQF, BRC). */
export interface CertificationReadinessInput {
  /** Certifications this retailer requires for this category/product. */
  requiredCertifications: CertificationType[];
  /** Certifications the brand currently holds. */
  heldCertifications: CertificationType[];
}

export interface CertificationFacts {
  requiredCertifications: CertificationType[];
  heldCertifications: CertificationType[];
  missingCertifications: CertificationType[];
}

// ---------------------------------------------------------------------------
// Timing — 13%
// ---------------------------------------------------------------------------

/** Is the category submission window open? When is the next reset cycle? */
export interface TimingInput {
  submissionWindowOpen: boolean;
  /**
   * Days until the next category reset/submission window opens. `null` if
   * unknown/not published. Ignored when `submissionWindowOpen` is true.
   */
  daysUntilNextWindow: number | null;
}

export interface TimingFacts {
  submissionWindowOpen: boolean;
  daysUntilNextWindow: number | null;
}

// ---------------------------------------------------------------------------
// Velocity — 10%
// ---------------------------------------------------------------------------

/** Existing units-per-store-per-week (UPSPW) data. Zero if DTC-only. */
export interface VelocityInput {
  /** True if the brand has no retail placement yet — no UPSPW data can exist. */
  isDtcOnly: boolean;
  /** UPSPW from existing retail placement. Ignored (treated as 0) if `isDtcOnly`. */
  unitsPerStorePerWeek?: number;
}

export interface VelocityFacts {
  isDtcOnly: boolean;
  /** Effective UPSPW used for scoring — always 0 when `isDtcOnly` is true. */
  unitsPerStorePerWeek: number;
}

// ---------------------------------------------------------------------------
// Fulfillment Readiness — 9%
// ---------------------------------------------------------------------------

/** Co-manufacturer in place? Lead time under 30 days? Capacity for regional rollout? */
export interface FulfillmentReadinessInput {
  hasCoManufacturer: boolean;
  /** Current production lead time, in days. */
  leadTimeDays: number;
  hasRegionalProductionCapacity: boolean;
}

export interface FulfillmentFacts extends FulfillmentReadinessInput {
  /** Whether leadTimeDays clears the PRD's "under 30 days" bar. */
  meetsLeadTimeRequirement: boolean;
}

// ---------------------------------------------------------------------------
// Aggregate shapes
// ---------------------------------------------------------------------------

export interface ScoringInput {
  margin: MarginReadinessInput;
  distributor: DistributorReadinessInput;
  certification: CertificationReadinessInput;
  timing: TimingInput;
  velocity: VelocityInput;
  fulfillment: FulfillmentReadinessInput;
}

export interface DimensionScores {
  margin: DimensionScore<MarginFacts>;
  distributor: DimensionScore<DistributorFacts>;
  certification: DimensionScore<CertificationFacts>;
  timing: DimensionScore<TimingFacts>;
  velocity: DimensionScore<VelocityFacts>;
  fulfillment: DimensionScore<FulfillmentFacts>;
}

/**
 * PRD §6.1 FR-01 weights, corrected to sum to exactly 100 (the original
 * table summed to 110% before Fulfillment was rebalanced in). Keys match the
 * `Assessment` model's `*Score` column prefixes (`marginScore`, etc.) and
 * `blockerDimension`'s expected values one-for-one.
 */
export const DIMENSION_WEIGHTS = {
  margin: 27,
  distributor: 23,
  certification: 18,
  timing: 13,
  velocity: 10,
  fulfillment: 9,
} as const satisfies Record<string, number>;

export type DimensionKey = keyof typeof DIMENSION_WEIGHTS;

/** Canonical, stable iteration/tie-break order — highest weight first. */
export const DIMENSION_ORDER: readonly DimensionKey[] = [
  "margin",
  "distributor",
  "certification",
  "timing",
  "velocity",
  "fulfillment",
];
